### ISSUE TITLE
.NET Core 2.2 end of Life

### ISSUE THREAD

**Issue by duncanworthy** [slang25/Paket.CredentialProvider.Gen2Support#3]
On the Releases, the only package published is built to target .NET Core 2.2.

The project file has been updated to .NET 5.0, but no release package has been created for that.

**Comment by Flohack74** [comment]
Its easy to recompile, even for .NET 6.0 - but I agree either there should be a release at least once a year to update dependencies and framework, or mark this project as inactive.

**Comment by Flohack74** [comment]
The latest release is now on net8.0 so I guess this can be closed :)
