### ISSUE TITLE
Interactive login workflow in Windows?

### ISSUE THREAD

**Issue by Flohack74** [slang25/Paket.CredentialProvider.Gen2Support#4]
Hello,

while your solution works very well also on Windows machines with Azure, it is a bit cumbersome to follow the browser link and enter a code every time the token expires. Is there a way to detect Azure AND Windows and to avoid it but just let the Windows auth pop up ? Thx!

BR Florian

**Comment by flole1974** [comment]
Hello, this is still an issue for us, when the tokens stored by the Microsoft provider expire, there is no way to let the user log in again because as it seems the credential provider(s) cannot show the interactive login window...

**Comment by flole1974** [comment]
Ok I found the problem :) - I will send you a PR from my main account. Could you please take a look at it? Thanks!

**Comment by Flohack74** [comment]
Fixed by https://github.com/slang25/Paket.CredentialProvider.Gen2Support/pull/8 - so I close this here. Thanks!
